-- Company :      UNAM
-- Project :      icar-global.DM1
-- Author :       Moreno Tagle Ivan Raphael
--                Rodriguez Garcia Alan Julian
-- Date Created : Monday, June 05, 2017 11:31:52
-- Target DBMS : Oracle 12c


connect <user>/<user>@AJRGBD_S1

--SITIO 1
--Replicados
--NO synonym

--Weas :'v
CREATE OR REPLACE SYNONYM hist_stat_lap_f2 FOR HIST_STAT_LAP_F2_AJRG_S1@AJRGBD_S1;
CREATE OR REPLACE SYNONYM lap_inv_2 FOR LAP_INV_F2_AJRG_S1@AJRGBD_S1;
CREATE OR REPLACE SYNONYM laptop_f1 FOR  LAPTOP_F1_AJRG_S1@AJRGBD_S1;
CREATE OR REPLACE SYNONYM serv_lap_f1 FOR SERV_LAP_F1_AJRG_S1@AJRGBD_S1;
CREATE OR REPLACE SYNONYM sucursal_f1 FOR SUCURSAL_F1_AJRG_S1@AJRGBD_S1;
CREATE OR REPLACE SYNONYM suc_tall_f1 FOR SUC_TALLER_F1_AJRG_S1@AJRGBD_S1;
CREATE OR REPLACE SYNONYM suc_venta_f1 FOR SUC_VENTA_F1_AJRG_S1@AJRGBD_S1;

--SITIO 2

--Weas :'v
CREATE OR REPLACE SYNONYM hist_stat_lap_f1 FOR HIST_STAT_LAP_F1_AJRG_S2@AJRGBD_S2;
CREATE OR REPLACE SYNONYM laptop_f4 FOR LAPTOP_F4_AJRG_S2@AJRGBD_S2;
CREATE OR REPLACE SYNONYM serv_lap_f4 FOR SERV_LAP_F4_AJRG_S2@AJRGBD_S2;
CREATE OR REPLACE SYNONYM sucursal_f2 FOR SUCURSAL_F2_AJRG_S2@AJRGBD_S2;
CREATE OR REPLACE SYNONYM suc_taller_f2 FOR SUC_TALLER_F2_AJRG_S2@AJRGBD_S2;
CREATE OR REPLACE SYNONYM suc_venta_f2 FOR SUC_VENTA_F2_AJRG_S2@AJRGBD_S2;

--SITIO 3

CREATE OR REPLACE 

--Weas :'v


